#!/usr/bin/env bash
#
# brew-audit.sh — categorized inventory of your Homebrew leaves, with an overlap
# (redundant-tool) watch and a drift (installed-vs-declared) report. Read-only.
#
# Writes a Markdown catalog (default: ~/Projects/mac-setup/setup/PACKAGES.md) and prints a
# short summary. Re-run anytime to re-snapshot.
#
# Usage:  ./brew-audit.sh [output.md]
# Env:    PKGYAML=<path to chezmoi packages.yaml>   (auto-detected by default)

set -uo pipefail
eval "$(/opt/homebrew/bin/brew shellenv)" 2>/dev/null || true

PKGYAML="${PKGYAML:-$HOME/.local/share/chezmoi/.chezmoidata/packages.yaml}"
OUT="${1:-$HOME/Projects/mac-setup/setup/PACKAGES.md}"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

brew leaves        | sort > "$tmp/leaves"
brew list --formula | sort > "$tmp/installed"
# tap-normalized leaf names (user/tap/<name> -> <name>) for drift comparison
sed 's|.*/||' "$tmp/leaves" | sort -u > "$tmp/leaves_norm"

# Declared brew names from packages.yaml, normalized to the leaf name (strip any
# tap prefix like `user/tap/<name>` -> `<name>`).
if [[ -r "$PKGYAML" ]]; then
  awk '/^  brews:/{f=1;next} /^  casks:/{f=0} f && /^    - /{gsub(/^    - /,""); sub(/.*\//,""); print}' \
    "$PKGYAML" | sort -u > "$tmp/declared"
else
  : > "$tmp/declared"
fi

# "name: description" for every leaf (single batched brew call).
xargs brew desc < "$tmp/leaves" 2>/dev/null > "$tmp/desc"

# --- categorize each leaf by keyword heuristics on name+description ---------
categorize() {
  local h
  h=$(printf '%s %s' "$1" "$2" | tr '[:upper:]' '[:lower:]')
  case "$h" in
    *monitor*|*htop*|*"graphical metrics"*|*"system metrics"*)  echo "System monitors";;
    *"shell history"*)                                          echo "Shell history";;
    *multiplexer*|*"terminal workspace"*)                       echo "Terminal multiplexers";;
    *prompt*)                                                   echo "Prompt";;
    *"file manager"*)                                           echo "File managers";;
    *git*)                                                      echo "Git";;
    *search*|*grep*|*"similar to ack"*|*"alternative to find"*) echo "Search / find";;
    *json*|*yaml*|*csv*)                                        echo "Data (JSON/YAML)";;
    *completion*|*completer*)                                   echo "Completions";;
    *pager*)                                                    echo "Pagers";;
    *container*|*docker*)                                       echo "Containers";;
    *vim*|*editor*)                                             echo "Editors";;
    *make*|*compiler*|*format*|*build*|*cmake*)                echo "Build / dev";;
    *cat*|*" ls "*|*" du "*|*"hex viewer"*|*tree*|*directories*) echo "File / CLI utils";;
    *calculator*|*ascii*|*aquarium*|*animation*)               echo "Fun / misc";;
    *history*)                                                  echo "Shell history";;
    *)                                                          echo "Other";;
  esac
}

while IFS= read -r line; do
  name="${line%%:*}"; desc="${line#*: }"
  printf '%s\t%s\t%s\n' "$(categorize "$name" "$desc")" "$name" "$desc"
done < "$tmp/desc" | sort > "$tmp/cat"

# --- known redundancy clusters (NAME:member member member) ------------------
CLUSTERS=(
  "System monitors:bottom glances zenith"
  "Shell history:atuin mcfly"
  "Terminal multiplexers:tmux zellij"
  "Code search:ripgrep the_silver_searcher"
)

# ordered category display
CATEGORIES="System monitors|Shell history|Terminal multiplexers|Search / find|Git|Prompt|File managers|Pagers|Data (JSON/YAML)|Completions|Containers|Editors|Build / dev|File / CLI utils|Fun / misc|Other"

n_leaves=$(wc -l < "$tmp/leaves" | tr -d ' ')
n_inst=$(wc -l < "$tmp/installed" | tr -d ' ')
n_decl=$(wc -l < "$tmp/declared" | tr -d ' ')

{
  echo "# Homebrew Package Catalog"
  echo
  echo "_Generated by \`brew-audit.sh\` on $(date '+%Y-%m-%d %H:%M')._"
  echo
  echo "**$n_leaves** leaves (top-level) · **$n_inst** total installed (incl. deps) · **$n_decl** declared in \`packages.yaml\`."
  echo

  # Overlap watch
  echo "## ⚠️ Overlap watch (redundant tools)"
  echo
  any_overlap=0
  for c in "${CLUSTERS[@]}"; do
    label="${c%%:*}"; members="${c#*:}"
    present=""
    for m in $members; do
      grep -qx "$m" "$tmp/leaves" && present="$present $m"
    done
    cnt=$(echo $present | wc -w | tr -d ' ')
    if [ "$cnt" -gt 1 ]; then
      any_overlap=1
      echo "- **$label** — $cnt installed:$present"
    fi
  done
  [ "$any_overlap" -eq 0 ] && echo "- None — no known redundant clusters have >1 member installed. 🎉"
  echo

  # Categories
  echo "## Inventory by category"
  echo
  IFS='|' read -r -a cats <<< "$CATEGORIES"
  for cat in "${cats[@]}"; do
    rows=$(awk -F'\t' -v c="$cat" '$1==c' "$tmp/cat")
    [ -z "$rows" ] && continue
    echo "### $cat"
    echo "$rows" | awk -F'\t' '{printf "- **%s** — %s\n", $2, $3}'
    echo
  done

  # Drift
  echo "## Drift"
  echo
  echo "### Installed top-level but NOT declared in packages.yaml"
  extra=$(comm -23 "$tmp/leaves_norm" "$tmp/declared")
  if [ -n "$extra" ]; then
    echo "$extra" | while read -r p; do
      d=$(grep -m1 "^$p:" "$tmp/desc" 2>/dev/null); d="${d#*: }"
      echo "- **$p** — ${d:-?}"
    done
  else
    echo "- (none)"
  fi
  echo
  echo "### Declared in packages.yaml but NOT installed"
  missing=$(comm -23 "$tmp/declared" "$tmp/installed")
  if [ -n "$missing" ]; then
    echo "$missing" | while read -r p; do echo "- **$p**"; done
  else
    echo "- (none)"
  fi
} > "$OUT"

echo "Wrote $OUT"
echo "  leaves=$n_leaves  installed=$n_inst  declared=$n_decl"
grep -A20 "Overlap watch" "$OUT" | grep '^- ' | head
